### PR TITLE
Improvements to the segmenter code + some small fixes

### PR DESCRIPTION
**Pull request by hhadian**
The main update is a function that computes the total logprob which we can call during the algorithm to see how it changes.
The total logprob is always improved with each merge.
With the new changes, I guess I'll need to change `segment.py` to concat the nnet outputs for all the crops of an input image and run the algorithm on the whole image, is that right?

### CODE REVIEW

**Comment by danpovey** [comment]
No, you won't have to splice together any crops.
We discussed this at the meeting- I should have updated you before.

My original plan was to just run the images at their natural size (or possibly reduced size according to some maximum dimension) through the network, since convnets naturally allow variable size input.  But it turns out Unet is different, it requires powers of two.
The current plan is to actually not do cropping during training, but to size the test and train image so that their larger side is a specified value (e.g. 256 or 512), and then pad with zeros to make them square. 
So we'll be both training and testing on fixed-size images.
Obviously we may need to post-process the output regions to be valid for the original image, for the downstream application.  But we can worry about that later.

**Comment by hhadian** [comment]
Oh, OK. But the current plan is not implemented yet, right? Because the current code seems to make crops.

**Comment by danpovey** [comment]
Yes, it's not implemented yet.
But we should be able to change it just by changing the data preparation--
if the desired training image size equals the dimension of the dumped
images, it should just not do anything.

**Comment by hhadian** [comment]
OK. Then, I guess @aarora8 could try the segmener on MADCAT. 
BTW, is anyone on the team working on evaluation?

**Comment by aarora8** [comment]
Ok, thanks. I will try the segmenter on MADCAT.

**Pull request merged**
