### PR TITLE
added scoring scripts for dsb2018

### PR DESCRIPTION
**Pull request by YiwenShaoStephen**
Now we can run from start to end and get a detailed result statistic.
Concretely, in exp/unet_../segment we have:
img/ : visualized predicted mask for each image
rle/: run-length encoding result for each image
submission.csv: aggregated rle results for all data  
result.txt: statistical evaluation result, including: final mean average precision and average precision for each image

The algorithm for computing IOU in scoring.py is well optimized. It's much much faster than the naive algorithm given by madcat which does a logical and/or over two binary masks. It reduces the evaluation time from more than 1 day to just seconds now. But I'm not perfectly sure it's the fastest and bug-free. I didn't find reference online.

### CODE REVIEW

**Comment by danpovey** [comment]
Great!  merging.

**Comment by danpovey** [comment]
Yiwen, what do you mean by the algorithm given by madcat?
I'm looking at Ashish's scoring code and it seems to use polygons from the
shapely library; I don't see binary operations over points.  (I do see the
use of an '&' operator but I assume it is something overloaded by the
shapely library).

However, Ashish's code does need better documentation.

**Comment by YiwenShaoStephen** [comment]
It's over here [https://github.com/waldo-seg/waldo/blob/master/egs/madcat_arabic/v1/scoring/scoring_utils.py#L53](url)

**Comment by aarora8** [comment]
We can use shapely library if the input is in text format (rectangle coordinates). But if we want to compute IOU value based on actual mask and predicted mask then it is completely based on numpy array operations. Yeah, Yiwens implementation for computing IOU value from a mask and predicted mask is faster as compared to madcat implementation since it is based on run-length encoding as compared to matrix level (and/ or) operations.

**Comment by danpovey** [comment]
That sounds super slow.  Are you at least limiting the masks to the
bounding boxes of where they are nonzero?  You could make it much faster by
doing that-- maybe creating some Python object corresponding to a bounding
mask with offsets for where its (0,0) co-ordinate lies, with stored area an
an operation to get the overlap with a similar object.

**Comment by aarora8** [comment]
Thanks, I am not doing it currently, but i will do it.

**Pull request merged**
