### PR TITLE
Madcat_arabic: Adding function to view ground truth and predicted BBox on original image

### PR DESCRIPTION
**Pull request by ChunChiehChang**
Example of the output is shown below. The only problem is that the scripts are now required to save the original image and dimensions. This causes ./local/process_data.py to be slower.
@aarora8 
aaw_arb_20070104 0028_1_ldc0088_orig

### CODE REVIEW

**Comment by danpovey** [comment]
That looks great!
Can you make it optional?  Or just run for a few images by default, maybe,
and option to do them all?

Incidentally (and it's great that you did this, or I would not have noticed
the issue), I notice that some of the little horizontal lines that indicate
the letter
(I think these are a short form of pairs of dots),  are just outside the
bounding boxes for their text lines.  This will likely cause
misrecognition.  I think what we should
do is set up the script that processes the data to add a little to the
bounding boxes before extracting the features-- for instance (and this
could be an option at
the script level, it could add a boundary of 0.1 times (the height of the
text line) to the top, bottom and sides of the text line.

If the resulting boxes were partly outside the image, we'd deal with it by
padding or reflection or something.

Dan

**Comment by danpovey** [comment]
... although that other stuff, obviously, is a Kaldi issue, not a Waldo
issue.

**Comment by aarora8** [comment]
It is looking very good/informative.

**Comment by hhadian** [comment]
This looks very nice!
I opened the image in a new window and it's much bigger than my screen. I guess it's better if you could scale it down to a more reasonable size (e.g. height=1000)

**Comment by ChunChiehChang** [comment]
The image size currently in use is the original size of the image. I can scale the size of the image down to something smaller.

**Pull request merged**
